name: release

on:
  push:

env:
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}

jobs:
  releasse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release to bintray
        run: |
          sbt publish
          sbt bintrayRelease